**DATA STRUCTURES**

Python data structures are essentially containers for different kinds of data.

Python provides a variety of data structures that are used efficiently for storing and manipulating data. Some of the most frequently used data structures include:

**Lists**: Lists are ordered collections that can store heterogeneous elements. They are commonly used for storing sequences of data, such as numerical values or strings. Lists are mutable, you can modify their elements after creation.

**NumPy Arrays**: NumPy is a fundamental package for numerical computations in Python. It provides the ndarray (n-dimensional array) data structure, which allows efficient manipulation of arrays of homogeneous data types. NumPy arrays are particularly useful for mathematical and statistical operations.

**Dictionaries**: Dictionaries are collections of key-value pairs. They are used for mapping unique keys to associated values. In data science, dictionaries can be used for tasks like storing metadata or creating lookup tables.

**Sets:** Sets are unordered collections of unique elements. They are useful for tasks that involve working with distinct values, such as removing duplicates from a dataset.

**Tuples**: Tuples are similar to lists, but they are immutable, meaning their elements cannot be changed after creation. They are often used to represent fixed collections of related data.

**TYPE CONVERSION** **:**  It functions to directly convert one data type to another.

When converting between different data structures, consider the specific properties and use cases of each structure. The choice of conversion depends on your intended use of the data.

Python provides built-in functions to convert one data type to another. Here are the key conversion functions:

int(): converts a value to an integer

float(): converts a value to a float

str(): converts a value to a string

bool(): converts a value to a boolean

**Conversion of int () to float() , str() , bool()**

In [ ]:
a = 45              #int to float
print(float(a))

b = 125             #int to string
print(str(b))

c = 1               #int to bool
print(bool(c))


45.0
125
True


*   For the conversion to float, the integer is converted to a floating-point number by adding a decimal point and zero fraction.
*   For the conversion to str, the integer is converted to its string representation.
*   For the conversion to bool, any non-zero integer value will be treated as True, while a value of 0 will be treated as False.





**Conversion of float() to int() , str() , bool()**

In [ ]:
d = 25.5          #float to int
print(int(d))

e = 12.6          #float to str
print(str(e))

f = 33.2          #float to bool
print(bool(f))

25
12.6
True


*  For the conversion to int, the decimal part of the floating-point number is truncated, resulting in an integer value.

*  For the conversion to str, the floating-point number is converted to its string representation.

*   For the conversion to bool, any non-zero value (including non-zero floats) will be treated as True, while a value of 0.0 will be treated as False.






**Conversion of str() to int() , float() , bool()**


In [ ]:
g = "10"          # str to int
print(int(g))

h = "65"          # str to float
print(float(h))

i = "True"        # str to bool
print(bool(i))

10
65.0
True



*   For the conversion to int, the string representing an integer is converted to an actual integer.
*   For the conversion to float, the string representing a floating-point number is converted to a floating-point number
*   For the conversion to bool, the strings "True" and "False" are converted to their corresponding boolean values, while any non-empty string is considered True, and an empty string is considered False.





**Conversion of bool() to int() , float() , str()**

In [ ]:
k = True          # bool to int
print(int(k))

l = True          # bool to float
print(float(l))

m = True          # bool to str
print(str(m))


1
1.0
True


**List**

*  A list is an ordered, mutable collection of elements.Syntax includes
squarebrackets [ , ] with ‘,’ separated data.
*  A list can be created using the list( ) function or simple assignment to [ .
*  An empty list can be created by l = [ ].It is an ordered collection of data.
*  Duplicate data entry is allowed in a List.Has integer based indexing that starts from ‘0’.



**Conversion of list() to numpy array() , dict() , tuple() , set()**

In [ ]:
import numpy as np

j = [1,2,3,4,5]       # list to Numpy array
jj = np.array(j)
print(jj)
type(jj)

[1 2 3 4 5]


numpy.ndarray

*  The Python list [1, 2, 3, 4, 5] is converted to a NumPy array using the np.array() function.


In [ ]:
n = ['a', 'b', 'c','d']     # list to dict
print(dict.fromkeys(n,2))

{'a': 2, 'b': 2, 'c': 2, 'd': 2}


*  You can convert a list to a dictionary where the list items become the dictionary keys. To do this, you need to provide values for the keys as well. The list ['a', 'b', 'c','d'] is converted to a dictionary where each list item becomes a dictionary key with an initial value of 0.


*  The fromkeys() method returns a dictionary with the specified keys and the specified value.Syntax is dict.fromkeys(keys, value)



In [ ]:
o = [1,2,3,4,5]             #list to tuple
print(tuple(o))

(1, 2, 3, 4, 5)


*  the list [1, 2, 3, 4, 5] is converted to a tuple using the tuple() function.


In [ ]:
p = [1,2,3,4,5]             # list to set
print(set(p))

{1, 2, 3, 4, 5}


*  To convert a list to a set, you can use the set() function. This will remove any duplicate elements and provide an unordered collection of unique elements. The list [1, 2, 2, 3, 3, 4, 5] is converted to a set using the set() function, resulting in a set of unique elements.



**Tuple**

*   A tuple is an ordered, immutable collection of elements.
*   Syntax includes curved brackets ( , ) with ‘,’ separated data.
*   An empty tuple can be created by t = ().It is also an ordered collection of data.
*   Duplicate data entry is allowed in a Tuple.Being immutable, it cannot be added , deleted , sorted


**Conversion of Tuple() to numpy array() , dict() , list() , set()**

In [ ]:
q = (1,2,3,4,5)           # tuple to Numpy array
qq = np.array(q)
print(qq)
type(qq)

[1 2 3 4 5]


numpy.ndarray

*  the Python tuple (1, 2, 3, 4, 5) is converted to a NumPy array using the np.array() function.


In [ ]:
r = (('a',1),('b',2),('c',3))   # tuple to dict
print(dict(r))

{'a': 1, 'b': 2, 'c': 3}


*   To convert a tuple to a dictionary, you need to have key-value pairs within the tuple. You can then use these pairs to create a dictionary.the tuple (('a', 1), ('b', 2), ('c', 3)) is converted to a dictionary where each tuple's first element becomes a key, and the second element becomes its corresponding value.



In [ ]:
s = (1,2,3,4,5)      # tuple to list
print(list(s))

[1, 2, 3, 4, 5]


*  the tuple (1, 2, 3, 4, 5) is converted to a list using the list() function.


In [ ]:
t = (1,2,3,4,5)         # tuple to set
print(set(t))

{1, 2, 3, 4, 5}


*  the tuple (1, 2, 2, 3, 3, 4, 5) is converted to a set using the set() function, resulting in a set of unique elements.



**Set**

*  A set is an unordered collection of unique elements.Syntax includes curly brackets { , } with ‘,’ separated data.
*  A set dictionary can be created using the set() function.An empty set can be created by s = set().
*  All elements are unique in a Set.
*  Does NOT have an index based mechanism.




**Conversion of set() to numpy array() , dict() , list() , tuple()**

In [ ]:
import numpy as np

ss = {1, 2, 3, 4, 5}              # set to list to Numpy array
pp = np.array(list(ss))
print(pp)
type(pp)


[1 2 3 4 5]


numpy.ndarray

* the Python set {1, 2, 3, 4, 5} is first converted to a list using list(python_set) and then to a NumPy array using the np.array() function.
*  Numpy expects the argument to be a list, it doesn't understand the set type so it creates an object array






In [ ]:
rr = {('a',1),('b',2),('c',3)}        # set to dict
print(dict(rr))

{'b': 2, 'c': 3, 'a': 1}


* the set {('a', 1), ('b', 2), ('c', 3)} is converted to a dictionary where each set element becomes a key-value pair.


In [ ]:
u = {1,2,3,4,5}               #set to list
print(list(u))

[1, 2, 3, 4, 5]


*  the set {1, 2, 3, 4, 5} is converted to a list using the list() function.


In [ ]:
uu = {1,2,3,4,5}            #set to tuple
print(tuple(uu))

(1, 2, 3, 4, 5)


*   the set {1, 2, 3, 4, 5} is converted to a tuple using the tuple() function.



**Dictionary**


*   A dictionary is an unordered collection of key-value pairs.
*   Syntax includes curly brackets { , } with ‘,’ separated key-value data.A dictionary can be created using the dict() function.
*  An empty dictionary can be created by {}.
*  Keys are unique, but two different keys CAN have the same value.



**Conversion of dict() to numpy array() , set() , list() , tuple()**

In [ ]:
x = {'a': 1, 'b': 2, 'c': 3}                    # dict to Numpy array
arr = np.array(list(x.items()))
print(arr)
type(arr)

[['a' '1']
 ['b' '2']
 ['c' '3']]


numpy.ndarray

*  The dict.items() method in Python is used to retrieve the key-value pairs from a dictionary as a list of tuples. Each tuple in the list represents a key-value pair, where the first element of the tuple is the key, and the second element is the corresponding value.



In [ ]:
y = {'a': 1, 'b': 2, 'c': 3}                    # dict to Numpy array
y_arr = np.array(list(y.values()))
print(y_arr)
type(y_arr)


[1 2 3]


numpy.ndarray

*  To convert a dictionary to a NumPy array, you can extract the values from the dictionary using the .values() method and then convert them to a NumPy array using the numpy.array() function.


In [ ]:
z = {'a': 1, 'b': 2, 'c': 3}                    # dict to set

z1 = set(z.keys())  # Set of keys
z2 = set(z.values())  # Set of values
z3 = set(z.items())    # Set of key-value pairs

print(z1)
print(z2)
print(z3)

{'a', 'c', 'b'} <class 'set'>
{1, 2, 3}
{('b', 2), ('c', 3), ('a', 1)}


* converting a dictionary directly to a set will only include the keys of the dictionary. If you want to include the values or key-value pairs in the set, we need to specify which part of the dictionary you want to include.
* different sets are created from the dictionary's keys, values, and items.



In [ ]:
l1 = {'a': 1, 'b': 2, 'c': 3}                       # dict to list

l2= list(l1.keys())        # List of keys
l3= list(l1.values())  # List of values
l4 = list(l1.items())    # List of key-value pairs

print(l2)
print(l3)
print(l4)

['a', 'b', 'c']
[1, 2, 3]
[('a', 1), ('b', 2), ('c', 3)]


* Converting a dictionary to a list by default includes the keys. If you want to include the values or key-value pairs in the list, We can use the .values() or .items() methods.
* different lists are created from the dictionary's keys, values, and items.



In [ ]:
y1= {'a': 1, 'b': 2, 'c': 3}                        # dict to tuple

y2 = tuple(y1)          # Tuple of keys
y3 = tuple(y1.values())    # Tuple of values
y4 = tuple(y1.items())      # Tuple of key-value pairs

print(y2)
print(y3)
print(y4)


('a', 'b', 'c')
(1, 2, 3)
(('a', 1), ('b', 2), ('c', 3))


* Similar to converting to a list, converting a dictionary to a tuple includes the keys by default. We can use the .values() or .items() methods to include the values or key-value pairs in the tuple.

* different tuples are created from the dictionary's keys, values, and items.



**Numpy array**


*  The most important feature is the N-dimensional array object is called ndarray. It describes the collection of homogeneous elements that uses zero-based indexing. All the elements of the ndarray have equal size of the memory block. Each element in ndarray is the object of a data type object (called dtype).

* NumPy is used to work with arrays. The array object in NumPy is called ndarray. We can create a NumPy ndarray object by using the array() function.

* To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray



**Conversion of numpy array() to dict() , set() , list() , tuple()**

In [ ]:
d_arr=np.array([1,2,3,4])       # Numpy array to list
d1 = list(d_arr)
print(d1 , type(d1))

[1, 2, 3, 4] <class 'list'>


* the NumPy array [1, 2, 3 , 4] is directly converted to a Python list


In [ ]:
x_arr=np.array([1,2,3,4])       # Numpy array to tuple
f1 = tuple(x_arr)
print(f1 , type(f1))

(1, 2, 3, 4) <class 'tuple'>


* the NumPy array [1, 2, 3, 4] is directly converted to a tuple using the tuple() function.



In [ ]:
q_arr = [1,2,2,4,5,4]           # Numpy array to set
w1 = set(q_arr)
print(w1, type(w1))

{1, 2, 4, 5} <class 'set'>


* the NumPy array [1, 2, 2, 4, 5, 4] is converted to a set containing only the unique values.



In [ ]:
# Example NumPy array
m_arr= np.array([10, 20, 30, 40, 50])           #Numpy array to dict

# Generating keys using enumerate
keys = ['a', 'b', 'c', 'd', 'e']

# Creating the dictionary
m_dict = dict(zip(keys, m_arr))

print(m_dict)

{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}


* We define the NumPy array named m_arr.
* We create a list of keys (keys) that we want to associate with each element of the array. Using the zip() function, we combine the keys list and the m_arr to create pairs of keys and values.
* We convert these pairs into a dictionary using the dict() function.
The resulting m_dict contains the key-value pairs where keys are taken from the keys list, and values are the elements of the m_arr.



*   Here in this case we can use enumerate() or zip() function
*   The enumerate() function provides both the index and value of each element in the array.
*  the zip() function is used to aggregate, or combine, multiple iterables



